name: Build botcoind Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    # Устанавливаем MSVC окружение
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    # Устанавливаем vcpkg
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg integrate install

    # Устанавливаем зависимости
    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg install boost:x64-windows
        .\vcpkg\vcpkg install openssl:x64-windows
        .\vcpkg\vcpkg install libevent:x64-windows
        .\vcpkg\vcpkg install sqlite3:x64-windows
        .\vcpkg\vcpkg install zlib:x64-windows

    # Конфигурация CMake
    - name: Configure
      run: >
        cmake -S . -B build
        -A x64
        -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
        -DCMAKE_BUILD_TYPE=Release

    # Сборка
    - name: Build
      run: cmake --build build --config Release --parallel

    # Загрузка exe файлов как artifact
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: botcoind-windows
        path: build/Release/*.exe
